# Generated by Django 5.2.16 on 2026-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, verbose_name='استفاده شده'),
        ),
    ]
