# Generated by Django 5.2.16 on 2026-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('normal', 'عادی'), ('grooming', 'داماد')], db_index=True, default='normal', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
