# Generated by Django 5.2.16 on 2026-07-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_category_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='یک جمله کوتاه برای کارت خدمت.', null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.CharField(blank=True, help_text='مثال: کاشت دقیق, خط\u200cکشی ریش, پایان\u200cکاری حوله\u200cی گرم', max_length=500, null=True, verbose_name='ویژگی\u200cها (با کاما جدا کنید)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر پس\u200cزمینه کارت خدمت. در صورت عدم انتخاب، از تصویر پیش\u200cفرض استفاده می\u200cشود.', null=True, upload_to='services/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
    ]
