# Generated by Django 5.2.16 on 2026-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_description_service_features_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
