# Generated by Django 5.2.16 on 2026-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display_price',
            field=models.IntegerField(default=1.2, verbose_name='قیمت برای نمایش: مثال: 5.3 یا پنج ملیون و سیصد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='قیمت به ریال'),
        ),
    ]
