# Generated by Django 5.2.16 on 2026-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_display_price_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='display_price',
            field=models.CharField(max_length=500, verbose_name='قیمت برای نمایش: مثال: 5.3 '),
        ),
    ]
