# Generated by Django 5.2.16 on 2026-07-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('status', models.CharField(choices=[('Pending', 'در انتظار'), ('Paid', 'پرداخت شده'), ('Delivered', 'تحویل داده شده'), ('Cancelled', 'لغو شده')], default='Pending', max_length=20, verbose_name='وضعیت')),
                ('shipping_name', models.CharField(max_length=150, verbose_name='نام گیرنده')),
                ('shipping_phone', models.CharField(max_length=15, verbose_name='شماره تماس گیرنده')),
                ('shipping_address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت زمان خرید')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
