# Generated by Django 5.2.16 on 2026-07-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('is_booked', models.BooleanField(default=False, verbose_name='رزرو شده')),
            ],
            options={
                'verbose_name': 'اسلات زمانی',
                'verbose_name_plural': 'اسلات\u200cهای زمانی',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BypassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد عبور از پیش\u200cپرداخت',
                'verbose_name_plural': 'کدهای عبور از پیش\u200cپرداخت',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='پیش\u200cپرداخت شده')),
                ('status', models.CharField(choices=[('Pending', 'در انتظار'), ('Confirmed', 'تایید شده'), ('Cancelled', 'لغو شده')], default='Pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
