# Generated by Django 5.2.16 on 2026-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('services', '0003_service_description_service_features_service_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='bookings', to='services.service', verbose_name='خدمات'),
        ),
    ]
