# Generated by Django 5.2.16 on 2026-07-29 11:14

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_service_booking_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
    ]
